services:
  mysql:
    image: mysql:8
    container_name: imobiliaria-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: imobiliaria
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_senha
    ports:
      - "3306:3306"
    volumes:
      - imobiliaria_data:/var/lib/mysql

volumes:
  imobiliaria_data: